### PR TITLE
Translate All Log To Eng

### PR DESCRIPTION
**Pull request by rtaserver**

### CODE REVIEW

**Comment by lededev** [comment]
额，你咋不把整个luci界面都翻译成英语的呢，虽然你很辛苦但真的不欣赏你这么搞，没必要，看英语日志至少降低我20%效率。

**Comment by xiaorouji** [comment]
Thank for you work, but it is recommended that you can make logic to i18n.

**Comment by Travel2Here** [comment]
朋友你这全是机器翻译的吧？质量不行哦
另外多语言配置 是在作者说的那个文件里做~也是luci的常识规范

**Comment by rtaserver** [comment]
> Thank for you work, but it is recommended that you can make logic to i18n.

OK, thanks for the input. because I'm still studying for a while, maybe just for personal purposes

**Pull request closed without merging**
